max_frames: 300
max_epoch: 15
batch_size: 48
margin: 0.2

eval_frames: 400
augment: False

## Training details
trainfunc: aamsoftmax

scale: 30

lr_decay: 0.95

pretrained_model_path: /home/nipunnirmal/data/WavLM-Base+.pt
weight_finetuning_reg: 0.01
LLRD_factor: 1.0
LR_Transformer: 2e-5
LR_MHFA: 5e-3

## Loss functions
nClasses: 1211

## Load and save
# save_path: exp/H_8_dim_cnn_alpha
save_path: exp/H_8_dim_cnn_new

## Model definition
model: Baseline.Spk_Encoder

nOut: 256
port: 6754

train_list: /home/nipunnirmal/data/train_list.txt
train_path: /home/nipunnirmal/data/wav/

test_list: /home/nipunnirmal/data/veri_test.txt
# test_list: /home/nipunnirmal/text-independent-speaker-verification-using-mine/infer.txt
test_path: /home/nipunnirmal/data/wav_test/

# alpha: 0.1
# beta: 0.5
# gamma: 0.05

alpha: 0.01
beta: 0.05
gamma: 0.005
# alpha: 1
# beta: 0
# gamma: 0

# test_list_percentage: 0.0009
# train_list_percentage: 0.05